Fix GitHub regressions in #69
Error message:

        'avatar': commit['author']['avatar_url'] if user['avatar_url'] is not None else ''
    UnboundLocalError: local variable 'user' referenced before assignment

Ref: https://github.com/ojacques/mkdocs-git-committers-plugin-2/pull/69